name: Deploy Firbase Functions

on:
  push:
    branches:
      - main # mainブランチにpushされたら実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # firebaseがサポートするバージョンを指定
      
      - name: Install dependencies
        run: npm ci # package.jsonに記載された依存関係をインストール

      - name: Instal ESLint
        run: npm install -g eslint 

      - name : Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy Firebase Functions
        run: firebase deploy --only functions --token $FIREBASE_TOKEN # Firebase Functionsをデプロイ
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # Firebase CLIの認証に必要なトークンを取得
          